package jp.datable.argo.workflow.client.models

data class CoreVolume(
    val name: String,
    val awsElasticBlockStore: CoreAWSElasticBlockStoreVolumeSource?,
    val azureDisk: CoreAzureDiskVolumeSource?,
    val azureFile: CoreAzureFileVolumeSource?,
    val cephfs: CoreCephFSVolumeSource?,
    val cinder: CoreCinderVolumeSource?,
    val configMap: CoreConfigMapVolumeSource?,
    val csi: CoreCSIVolumeSource?,
    val downwardAPI: CoreDownwardAPIVolumeSource?,
    val emptyDir: CoreEmptyDirVolumeSource?,
    val ephemeral: CoreEphemeralVolumeSource?,
    val fc: CoreFCVolumeSource?,
    val flexVolume: CoreFlexVolumeSource?,
    val flocker: CoreFlockerVolumeSource?,
    val gcePersistentDisk: CoreGCEPersistentDiskVolumeSource?,
    val gitRepo: CoreGitRepoVolumeSource?,
    val glusterfs: CoreGlusterfsVolumeSource?,
    val hostPath: CoreHostPathVolumeSource?,
    val iscsi: CoreISCSIVolumeSource?,
    val nfs: CoreNFSVolumeSource?,
    val persistentVolumeClaim: CorePersistentVolumeClaimVolumeSource?,
    val photonPersistentDisk: CorePhotonPersistentDiskVolumeSource?,
    val portworxVolume: CorePortworxVolumeSource?,
    val projected: CoreProjectedVolumeSource?,
    val quobyte: CoreQuobyteVolumeSource?,
    val rbd: CoreRBDVolumeSource?,
    val scaleIO: CoreScaleIOVolumeSource?,
    val secret: CoreSecretVolumeSource?,
    val storageos: CoreStorageOSVolumeSource?,
    val vsphereVolume: CoreVsphereVirtualDiskVolumeSource?
)
