package jp.datable.argo.workflow.client.models.openapi

data class EvEventSourceSpec(
    val amqp: EvAMQPEventSource? = null,
    val azureEventsHub: EvAzureEventsHubEventSource? = null,
    val bitbucket: EvBitbucketEventSource? = null,
    val bitbucketserver: EvBitbucketServerEventSource? = null,
    val calendar: EvCalendarEventSource? = null,
    val emitter: EvEmitterEventSource? = null,
    val eventBusName: String? = null,
    val file: EvFileEventSource? = null,
    val generic: EvGenericEventSource? = null,
    val github: EvGithubEventSource? = null,
    val gitlab: EvGitlabEventSource? = null,
    val hdfs: EvHDFSEventSource? = null,
    val kafka: EvKafkaEventSource? = null,
    val minio: EvS3Artifact? = null,
    val mqtt: EvMQTTEventSource? = null,
    val nats: EvNATSEventsSource? = null,
    val nsq: EvNSQEventSource? = null,
    val pubSub: EvPubSubEventSource? = null,
    val pulsar: EvPulsarEventSource? = null,
    val redis: EvRedisEventSource? = null,
    val redisStream: EvRedisStreamEventSource? = null,
    val replicas: Int? = null,
    val resource: EvResourceEventSource? = null,
    val service: EvService? = null,
    val slack: EvSlackEventSource? = null,
    val sns: EvSNSEventSource? = null,
    val sqs: EvSQSEventSource? = null,
    val storageGrid: EvStorageGridEventSource? = null,
    val stripe: EvStripeEventSource? = null,
    val template: EvTemplate? = null,
    val webhook: EvWebhookEventSource? = null
)
