package jp.datable.argo.workflow.client.models.openapi

data class WfTemplate(
    val activeDeadlineSeconds: String? = null,
    val affinity: CoreAffinity? = null,
    val archiveLocation: WfArtifactLocation? = null,
    val automountServiceAccountToken: Boolean? = null,
    val container: CoreContainer? = null,
    val containerSet: WfContainerSetTemplate? = null,
    val daemon: Boolean? = null,
    val dag: WfDAGTemplate? = null,
    val `data`: WfData? = null,
    val executor: WfExecutorConfig? = null,
    val failFast: Boolean? = null,
    val hostAliases: List<CoreHostAlias>? = null,
    val http: WfHTTP? = null,
    val initContainers: List<WfUserContainer>? = null,
    val inputs: WfInputs? = null,
    val memoize: WfMemoize? = null,
    val metadata: WfMetadata? = null,
    val metrics: WfMetrics? = null,
    val name: String? = null,
    val nodeSelector: Map<String, String>? = null,
    val outputs: WfOutputs? = null,
    val parallelism: Int? = null,
    val plugin: Any? = null,
    val podSpecPatch: String? = null,
    val priority: Int? = null,
    val priorityClassName: String? = null,
    val resource: WfResourceTemplate? = null,
    val retryStrategy: WfRetryStrategy? = null,
    val schedulerName: String? = null,
    val script: WfScriptTemplate? = null,
    val securityContext: CorePodSecurityContext? = null,
    val serviceAccountName: String? = null,
    val sidecars: List<WfUserContainer>? = null,
    val steps: List<List<WfWorkflowStep>>? = null,
    val `suspend`: WfSuspendTemplate? = null,
    val synchronization: WfSynchronization? = null,
    val timeout: String? = null,
    val tolerations: List<CoreToleration>? = null,
    val volumes: List<CoreVolume>? = null
)
